<?xml version="1.0" encoding="UTF-8"?>
<!--
========================================================================
DATOS DE IDENTIFICACIÓN:
Nombre de la Universidad: Universidad Virtual del Estado de Guanajuato (UVEG)
Nombre del estudiante: Emmanuel Martinez Zavaleta
Número de matrícula: 24026867
Nombre de Asesora o Asesor: Gabriela Garibay Mendoza
Nombre del Módulo: Calidad y Pruebas de Software
Nombre del Reto: Reto 5. Automatización de una pantalla login
Fecha de elaboración: 26/08/2026
========================================================================
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.uveg.calidad</groupId>
    <artifactId>Reto5_AutomatizacionLogin</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <selenium.version>4.18.1</selenium.version>
        <testng.version>7.9.0</testng.version>
        <maven.surefire.version>3.2.5</maven.surefire.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>${suiteXmlFile}</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>InicioDeSesion</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <suiteXmlFile>Inicio de sesion.xml</suiteXmlFile>
            </properties>
        </profile>
    </profiles>
</project>